name: conformance-checking
channels:
  - defaults
# these dependencies must be kept in sync with tox.ini
dependencies:
  - python=3.7
  - pip~=20.3.3
  - numpy~=1.19.2
  - pytest~=6.2.1
  - pytest-cov~=2.10.1
  - flake8~=3.8.4
  - pip:
    - pm4py~=2.1.2
    - pytest-randomly~=3.5.0
    - tox-conda~=0.5.0
    - black~=20.8b1
